apply plugin: 'com.android.application'

android {
    compileSdkVersion 33
    buildToolsVersion '32.0.0'

    defaultConfig {
        applicationId "com.azya.seiko.uc2000.lion"
        minSdkVersion 19
        targetSdkVersion 33
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    namespace 'com.azya.seiko.uc2000'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}
